# Generated by Django 6.0.5 on 2026-05-18 09:05

import froala_editor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', froala_editor.fields.FroalaField(verbose_name='内容')),
                ('news_type', models.CharField(choices=[('company', '企业新闻'), ('industry', '行业新闻'), ('notice', '通知公告')], default='company', max_length=20, verbose_name='新闻类型')),
                ('published_at', models.DateTimeField(verbose_name='发布时间')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
                'ordering': ('-published_at',),
            },
        ),
    ]
