# Generated by Django 6.0.5 on 2026-06-01 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='招聘岗位')),
                ('description', models.TextField(verbose_name='岗位要求')),
                ('publishDate', models.DateTimeField(default=datetime.datetime.now, max_length=20, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '招聘广告',
                'verbose_name_plural': '招聘广告',
                'ordering': ('-publishDate',),
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('personID', models.CharField(max_length=30, verbose_name='身份证号')),
                ('sex', models.CharField(default='男', max_length=5, verbose_name='性别')),
                ('email', models.EmailField(max_length=30, verbose_name='邮箱')),
                ('birth', models.DateField(default='2026-06-01', max_length=20, verbose_name='出生日期')),
                ('edu', models.CharField(default='本科', max_length=5, verbose_name='学历')),
                ('school', models.CharField(max_length=40, verbose_name='毕业院校')),
                ('major', models.CharField(max_length=40, verbose_name='专业')),
                ('position', models.CharField(max_length=40, verbose_name='申请职位')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='学习或工作经历')),
                ('photo', models.ImageField(upload_to='contact/recruit/%Y_%m_%d', verbose_name='个人照片')),
                ('status', models.IntegerField(choices=[(1, '未审'), (2, '通过'), (3, '未通过')], default=1, verbose_name='审核')),
                ('publishDate', models.DateTimeField(default=datetime.datetime.now, max_length=20, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '简历',
                'verbose_name_plural': '简历',
                'ordering': ('-status', '-publishDate'),
            },
        ),
    ]
