# Generated by Django 6.0.6 on 2026-06-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_alter_resume_birth_productimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.CharField(choices=[('家用机器人', '家用机器人'), ('智能监控机器人', '智能监控机器人'), ('工业机器人', '工业机器人')], max_length=50, verbose_name='产品类型'),
        ),
    ]
